### ISSUE TITLE
Parity with Laravel SerializesModels

### ISSUE THREAD

**Issue by rginnow** [CodeSleeve/holloway#6]
https://laravel.com/docs/10.x/queues#class-structure

Can we get a `SerializesEntities` trait that would handle a fresh call to the database just like described in the above docs? It would make it easier than trying to force a certain set of data into a job, or do the fresh call ourselves.

**Comment by tabennett** [comment]
Closing this. This is not an issue, it's not the job of Holloway data mapper (or any data mapper for that matter) to mange the serialization of your entities. No PR.
