### ISSUE TITLE
Update factories

### ISSUE THREAD

**Issue by rginnow** [CodeSleeve/holloway#8]
Our options to refactor some tests are limited due to the legacy factories package introduced during [The Bump to Laravel 8](https://github.com/CodeSleeve/holloway/commit/b52f612429df723e34b1211f905d2012dd6e8076)

Specifically, we're missing out on the ability to use [sequences.](https://laravel.com/docs/10.x/eloquent-factories#sequences)

This allows us to do things like this:
```php
$someCollection = collect([
  // ... some collection of an entity
]);

$differentCollection = collect(
  factory(AnEntity::class, 4)->sequence(function (Sequence $sequence) {
    return [
      "some_related_id" => $someCollection->get($sequence->index)->id
    ];
  })->create()
);
```

Adding even just this feature to Holloway factories would remove the need to manually loop through iterables to get to achieve the same goal:
```php
$someCollection = collect([
  // ... some collection of an entity
]);

$differentCollection = collect();

foreach ($someCollection as $someItem) { // or using $someCollection->each()
  $index = $someCollection
    ->filter(fn($item) => $item->id === $someItem->id)
    ->keys()
    ->first();

  $differentCollection->push(factory(AnEntity::class)->create([
    "some_related_id" => $someCollection->get($index)->id,
  ]));
}
```

**Comment by tabennett** [comment]
Closing this; This is not an issue and you haven't submitted a PR.
